### ISSUE TITLE
[BUG] Virtual fields included in query when using pow authentication package

### ISSUE THREAD

**Issue by axelclark** [aesmail/kaffy#104]
**Versions Used**
Kaffy: master
Phoenix: 1.5.3
Elixir: 1.10

**What's actually happening?**
When I go to my User index page, I get a Postgrex error.  The error is because the query is referencing virtual fields from `pow_user_fields()` included with the [pow](https://github.com/danschultzer/pow) user authentication project.  The  fields are referenced in the `WHERE` clause. See fields [here](https://github.com/danschultzer/pow/blob/master/lib/pow/ecto/schema/fields.ex).  Both `current_password` and `password` are virtual fields.

```elixir
defmodule Ex338.Accounts.User do
  @moduledoc false
  use Ecto.Schema
  use Ex338Web, :model

  use Pow.Ecto.Schema,
    password_min_length: 6,
    password_hash_methods: {&Bcrypt.hash_pwd_salt/1, &Bcrypt.verify_pass/2}

  use Pow.Extension.Ecto.Schema,
    extensions: [PowResetPassword, PowPersistentSession, PowInvitation]

  alias Ex338.Accounts.User

  schema "users" do
    field(:name, :string)
    field(:email, :string)
    field(:slack_name, :string)
    field(:admin, :boolean)
    has_many(:owners, Ex338.FantasyTeams.Owner)
    has_many(:submitted_trades, Ex338.Trades.Trade, foreign_key: :submitted_by_user_id)
    has_many(:trade_votes, Ex338.Trades.TradeVote)
    has_many(:fantasy_teams, through: [:owners, :fantasy_team])
    pow_user_fields()

    timestamps()
  end
end
```
Error message:
```bash
[info] GET /kaffy_admin/accounts/user
[debug] Processing with KaffyWeb.ResourceController.index/2
  Parameters: %{"context" => "accounts", "resource" => "user"}
  Pipelines: [:kaffy_browser, :protected, :admin, :remove_root_layout]
[debug] QUERY ERROR source="users" db=4.2ms queue=9.8ms idle=1818.4ms
SELECT u0."id", u0."name", u0."email", u0."slack_name", u0."admin", u0."invited_by_id", u0."invitation_accepted_at", u0."invitation_token", u0."password_hash", u0."inserted_at", u0."updated_at" FROM "users" AS u0 WHERE (u0."name" ILIKE $1) OR (u0."email" ILIKE $2) OR (u0."current_password" ILIKE $3) OR (u0."invitation_token" ILIKE $4) OR (u0."password" ILIKE $5) OR (u0."password_hash" ILIKE $6) OR (u0."slack_name" ILIKE $7) ORDER BY u0."id" DESC LIMIT $8 OFFSET $9 ["%%", "%%", "%%", "%%", "%%", "%%", "%%", 100, 0]
[info] Sent 500 in 216ms
[error] #PID<0.790.0> running Ex338Web.Endpoint (connection #PID<0.725.0>, stream id 17) terminated
Server: localhost:4000 (http)
Request: GET /kaffy_admin/accounts/user
** (exit) an exception was raised:
    ** (Postgrex.Error) ERROR 42703 (undefined_column) column u0.current_password does not exist

    query: SELECT u0."id", u0."name", u0."email", u0."slack_name", u0."admin", u0."invited_by_id", u0."invitation_accepted_at", u0."invitation_token", u0."password_hash", u0."inserted_at", u0."updated_at" FROM "users" AS u0 WHERE (u0."name" ILIKE $1) OR (u0."email" ILIKE $2) OR (u0."current_password" ILIKE $3) OR (u0."invitation_token" ILIKE $4) OR (u0."password" ILIKE $5) OR (u0."password_hash" ILIKE $6) OR (u0."slack_name" ILIKE $7) ORDER BY u0."id" DESC LIMIT $8 OFFSET $9
        (ecto_sql 3.4.4) lib/ecto/adapters/sql.ex:593: Ecto.Adapters.SQL.raise_sql_call_error/1
        (ecto_sql 3.4.4) lib/ecto/adapters/sql.ex:526: Ecto.Adapters.SQL.execute/5
        (ecto 3.4.5) lib/ecto/repo/queryable.ex:192: Ecto.Repo.Queryable.execute/4
        (ecto 3.4.5) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
        (kaffy 0.8.1) lib/kaffy/resource_query.ex:36: Kaffy.ResourceQuery.list_resource/2
        (kaffy 0.8.1) lib/kaffy_web/controllers/resource_controller.ex:60: KaffyWeb.ResourceController.index/2
        (kaffy 0.8.1) lib/kaffy_web/controllers/resource_controller.ex:1: KaffyWeb.ResourceController.action/2
        (kaffy 0.8.1) lib/kaffy_web/controllers/resource_controller.ex:1: KaffyWeb.ResourceController.phoenix_controller_pipeline/2
        (phoenix 1.5.3) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (ex338 0.0.1) lib/plug/error_handler.ex:65: Ex338Web.Router.call/2
        (ex338 0.0.1) lib/ex338_web/endpoint.ex:1: Ex338Web.Endpoint.plug_builder_call/2
        (ex338 0.0.1) lib/plug/debugger.ex:132: Ex338Web.Endpoint."call (overridable 3)"/2
        (ex338 0.0.1) lib/ex338_web/endpoint.ex:1: Ex338Web.Endpoint.call/2
        (phoenix 1.5.3) lib/phoenix/endpoint/cowboy2_handler.ex:65: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.8.0) /Users/jackclark/workspace/ex338/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.8.0) /Users/jackclark/workspace/ex338/deps/cowboy/src/cowboy_stream_h.erl:300: :cowboy_stream_h.execute/3
        (cowboy 2.8.0) /Users/jackclark/workspace/ex338/deps/cowboy/src/cowboy_stream_h.erl:291: :cowboy_stream_h.request_process/3
        (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**What should happen instead?**
Query should not include virtual fields.  It seems specific to how pow implements the fields.  I don't receive the error for other resources with virtual fields I've identified in other schemas.

**Comment by aesmail** [comment]
We shouldn't include virtual fields when querying that's for sure.
But the fact that it only happens with the POW schema needs more investigation.

**Comment by axelclark** [comment]
It looks like those fields are included in the list of filtered fields.  I’ll see if I can get more info about where they are coming from.

**Comment by axelclark** [comment]
I discovered the reason the pow fields caused the error is those fields are `string` types while the other virtual fields I have are `integer` types.

Here is the relevant section of code in kaffy.
https://github.com/aesmail/kaffy/blob/e8cd102052d8dc98264cea05a478a9c863eec8de/lib/kaffy/resource_schema.ex#L236-L249

The function `schema.__schema__(:fields)` does not return virtual fields, so when filtering the fields for search, we may need to make sure the field is included in that list of fields in addition to the field being `[:string, :textarea, :richtext]`.

**Comment by aesmail** [comment]
That makes sense!
Thanks for the debugging efforts 👍🏼
I'll push a fix later today.

**Comment by axelclark** [comment]
I have a fix prepped and will send as a pull request.  Feel free to adjust it, but it seems to resolve the issue.
