### ISSUE TITLE
[BUG] Schema fields of type `{:array, _}` can't be rendered in form view

### ISSUE THREAD

**Issue by whitedr** [aesmail/kaffy#130]
**Versions Used**
Kaffy: 0.9.0
Phoenix: 1.4.15
Elixir: 1.10.1

**What's actually happening?**
I'm using [Oban](https://github.com/sorentwo/oban) in my project and (purely for for debugging purposes) I'm trying to expose Oban.Job as a resource type in Kaffy.  One of the fields in this schema is "errors" which is a `{:array, :map}` ecto field type.  It looks like Kaffy doesn't array fields as I get the following exception:

```
08:00:31.994 [error] #PID<0.867.0> running AldAppWeb.Endpoint (connection #PID<0.838.0>, stream id 9) terminated
Server: localhost:4000 (http)
Request: GET /admin/planning/oban_job/3772
** (exit) an exception was raised:
    ** (ArgumentError) lists in Phoenix.HTML and templates may only contain integers representing bytes, binaries or other lists, got invalid entry: %{"at" => "2020-07-07T12:00:08.042202Z", "attempt" => 1, "error" => "** (ErlangError) Erlang error: :econnrefused\n    (elixir 1.10.1) lib/process.ex:765: Process.info/2\n    (oban 1.1.0) lib/oban/queue/executor.ex:110: Oban.Queue.Executor.current_stacktrace/0\n    (oban 1.1.0) lib/oban/queue/executor.ex:73: Oban.Queue.Executor.perform/2\n    (stdlib 3.11) timer.erl:197: :timer.tc/3\n    (oban 1.1.0) lib/oban/queue/executor.ex:13: Oban.Queue.Executor.call/2\n    (elixir 1.10.1) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2\n    (elixir 1.10.1) lib/task/supervised.ex:35: Task.Supervised.reply/5\n    (stdlib 3.11) proc_lib.erl:249: :proc_lib.init_p_do_apply/3\n"}
        (phoenix_html 2.14.2) lib/phoenix_html/safe.ex:81: Phoenix.HTML.Safe.List.to_iodata/1
        (phoenix_html 2.14.2) lib/phoenix_html/safe.ex:49: Phoenix.HTML.Safe.List.to_iodata/1
        (phoenix_html 2.14.2) lib/phoenix_html.ex:153: Phoenix.HTML.html_escape/1
        (elixir 1.10.1) lib/keyword.ex:832: Keyword.update!/4
        (phoenix_html 2.14.2) lib/phoenix_html/form.ex:826: Phoenix.HTML.Form.generic_input/4
        (kaffy 0.9.0) lib/kaffy/resource_form.ex:344: Kaffy.ResourceForm.kaffy_input/5
        (kaffy 0.9.0) lib/kaffy_web/templates/resource/show.html.eex:38: anonymous fn/4 in KaffyWeb.ResourceView."show.html"/1
        (elixir 1.10.1) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
        (kaffy 0.9.0) lib/kaffy_web/templates/resource/show.html.eex:36: KaffyWeb.ResourceView."show.html"/1
        (kaffy 0.9.0) lib/kaffy_web/templates/layout/app.html.eex:141: KaffyWeb.LayoutView."app.html"/1
        (phoenix 1.4.15) lib/phoenix/view.ex:410: Phoenix.View.render_to_iodata/3
        (phoenix 1.4.15) lib/phoenix/controller.ex:729: Phoenix.Controller.__put_render__/5
        (phoenix 1.4.15) lib/phoenix/controller.ex:746: Phoenix.Controller.instrument_render_and_send/4
        (kaffy 0.9.0) lib/kaffy_web/controllers/resource_controller.ex:1: KaffyWeb.ResourceController.action/2
        (kaffy 0.9.0) lib/kaffy_web/controllers/resource_controller.ex:1: KaffyWeb.ResourceController.phoenix_controller_pipeline/2
        (phoenix 1.4.15) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
        (ald_app 0.1.0) lib/ald_app_web/endpoint.ex:1: AldAppWeb.Endpoint.plug_builder_call/2
        (ald_app 0.1.0) lib/plug/debugger.ex:132: AldAppWeb.Endpoint."call (overridable 3)"/2
        (ald_app 0.1.0) lib/ald_app_web/endpoint.ex:1: AldAppWeb.Endpoint.call/2
        (phoenix 1.4.15) lib/phoenix/endpoint/cowboy2_handler.ex:42: Phoenix.Endpoint.Cowboy2Handler.init/4
```

**What should happen instead?**
I think it would be good if these field types were handled similar to `:map` field types and they are rendered in a text area as a json encoded string.  I know this may not be ideal for all use cases but could be a reasonable default behavior.

This diff seems to work for me:

```
diff --git a/lib/kaffy/resource_form.ex b/lib/kaffy/resource_form.ex
index a41c6c8..63a971b 100644
--- a/lib/kaffy/resource_form.ex
+++ b/lib/kaffy/resource_form.ex
@@ -159,6 +159,14 @@ defmodule Kaffy.ResourceForm do
 
         textarea(form, field, [value: value, rows: 4, placeholder: "JSON Content"] ++ opts)
 
+      {:array, _} ->
+        value =
+          data
+          |> Map.get(field, "")
+          |> Kaffy.Utils.json().encode!(escape: :html_safe, pretty: true)
+
+        textarea(form, field, [value: value, rows: 4, placeholder: "JSON Content"] ++ opts)
+
       :file ->
         file_input(form, field, opts)
```

Note: I did see the recent addition of custom form fields which I thought could be an option, but it looks like you need to own the schema in question to use that capability.

**Screenshots**

**Comment by Stefano1990** [comment]
This does not work for me:
![image](https://user-images.githubusercontent.com/224657/91632534-bada3f00-e9e1-11ea-9fa7-1d7313e3b4b8.png)

**Comment by aesmail** [comment]
@Stefano1990 are you using v0.9.0 or master?

**Comment by Stefano1990** [comment]
I'm using master now but still the same thing. Just says the field is "invalid". However, I might just be entering it wrong.

**Comment by aesmail** [comment]
@Stefano1990 double checking your type (`{:array, :map}`), maybe the array should include maps in order to be valid?
Something like:
```elixir
[ %{m: "male"}, %{f: "female"} ]
```

However, I feel what you want is `{:array, :string}` in which case the value of the field could be:
```elixir
["M", "F"]
```

**Comment by Stefano1990** [comment]
Yes, its an array of strings. However, I tried that including and without the square brackets, etc. but kaffy refuses it as "invalid". I guess something funky in the validation?

**Comment by aesmail** [comment]
Could you enter a record manually (e.g. via iex) and see if kaffy can read it and render it correctly in the form page? This would make it easier to pinpoint the issue.

**Comment by Stefano1990** [comment]
The record:
```elixir
%Backend.Events.Event{
  __meta__: #Ecto.Schema.Metadata<:loaded, "events">,
  allowed_gender_groups: ["M"],
  classifieds: #Ecto.Association.NotLoaded<association :classifieds is not loaded>,  
  comments: #Ecto.Association.NotLoaded<association :comments is not loaded>,        
  date: ~D[2020-09-03],
  description: "a long description",
  event_series: #Ecto.Association.NotLoaded<association :event_series is not loaded>,
  event_series_id: 1,
  guests: #Ecto.Association.NotLoaded<association :guests is not loaded>,
  id: 1,
  inserted_at: ~N[2020-08-05 18:29:46],
  name: "an event",
  number_of_guests: nil,
  reservations: #Ecto.Association.NotLoaded<association :reservations is not loaded>,
  reservations_allowed: true,
  reservations_open_at: ~U[2020-01-01 00:00:00.000000Z],
  slug: "an-event-03-09-2020",
  start_time: ~T[20:00:00],
  updated_at: ~N[2020-09-11 09:45:41]
}
```

This only works with some trickery:
```elixir
def changeset(event, attrs) do
    event
    |> cast(attrs, [:name, :description, :reservations_allowed, :reservations_open_at, :date, :start_time, :event_series_id, :allowed_gender_groups])
    |> cast_allowed_gender_groups(attrs, event)
    |> validate_required([:name, :description, :reservations_allowed, :reservations_open_at, :date, :start_time, :event_series_id, :allowed_gender_groups])
    |> put_slug()
  end
  
  def cast_allowed_gender_groups(changeset, attrs, event) do
    if Map.has_key?(attrs, :allowed_gender_groups) do # we are assigning a new allowed_gender_group value
      put_change(changeset, :allowed_gender_groups, attrs.allowed_gender_groups)
    else
      put_change(changeset, :allowed_gender_groups, event.allowed_gender_groups || []) # put the previous value or put an empty array
    end
  end
```

This works fine in the console:
```elixir
iex(51)> e |> Backend.Events.Event.changeset(%{allowed_gender_groups: ["M", "F", "MF"]}) |> Repo.update() 
[debug] QUERY OK db=15.0ms idle=624.9ms
UPDATE "events" SET "allowed_gender_groups" = $1, "updated_at" = $2 WHERE "id" = $3 [["M", "F", "MF"], ~N[2020-09-11 09:49:54], 1]
{:ok,
 %Backend.Events.Event{
   __meta__: #Ecto.Schema.Metadata<:loaded, "events">,
   allowed_gender_groups: ["M", "F", "MF"],
   classifieds: #Ecto.Association.NotLoaded<association :classifieds is not loaded>,
   comments: #Ecto.Association.NotLoaded<association :comments is not loaded>,
   date: ~D[2020-09-03],
   description: "a long description",
   event_series: #Ecto.Association.NotLoaded<association :event_series is not loaded>,
   event_series_id: 1,
   guests: #Ecto.Association.NotLoaded<association :guests is not loaded>,
   id: 1,
   inserted_at: ~N[2020-08-05 18:29:46],
   name: "an event",
   number_of_guests: nil,
   reservations: #Ecto.Association.NotLoaded<association :reservations is not loaded>,
   reservations_allowed: true,
   reservations_open_at: ~U[2020-01-01 00:00:00.000000Z],
   slug: "an-event-03-09-2020",
   start_time: ~T[20:00:00],
   updated_at: ~N[2020-09-11 09:49:54]
 }}
```

but does not work in kaffy:
![image](https://user-images.githubusercontent.com/224657/92906785-0a2e5f80-f425-11ea-9268-5a2c5c849f77.png)

**Comment by Stefano1990** [comment]
I still can't this to work btw.

**Comment by rootkc** [comment]
I have the exact same problem using Oban with Kaffy from master branch.
