### ISSUE TITLE
[BUG] Phoenix 1.7

### ISSUE THREAD

**Issue by ghenry** [aesmail/kaffy#258]
**Versions Used**
Kaffy: 0.9.2
Phoenix: 1.7.0-rc.2
Elixir: Elixir 1.14.1 (compiled with Erlang/OTP 24)

**What's actually happening?**

```
== Compilation error in file lib/kaffy_web/views/resource_view.ex ==
** (CompileError) lib/kaffy_web/views/resource_view.ex:4: module Phoenix.View is not loaded and could not be found. This may be happening because the module you are trying to load directly or indirectly depends on the current module
    (elixir 1.14.1) expanding macro: Kernel.use/2
    lib/kaffy_web/views/resource_view.ex:4: KaffyWeb.ResourceView (module)
could not compile dependency :kaffy, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile kaffy", update it with "mix deps.update kaffy" or clean it with "mix deps.clean kaffy"
```

**What should happen instead?**

Changes like so: https://blog.appsignal.com/2022/12/06/appsignal-for-phoenix-version-2.1.0-supports-phoenix-1.7.html

**Comment by maysam** [comment]
adding `phoenix_view` to the mix didn't help me either

I keep getting `UndefinedFunctionError at GET /admin
function AppWeb.Router.Helpers.kaffy_dashboard_path/2 is undefined (module AppWeb.Router.Helpers is not available)`

**Comment by ghenry** [comment]
Nah, this need core code update I think. I'm hoping to have a look soon.

**Comment by AodhanHayter** [comment]
> adding `phoenix_view` to the mix didn't help me either
> 
> I keep getting `UndefinedFunctionError at GET /admin function AppWeb.Router.Helpers.kaffy_dashboard_path/2 is undefined (module AppWeb.Router.Helpers is not available)`

Looks like the `AppWeb.Router.Helpers` module is not generated by default in 1.7. It can be enabled by passing `helpers: true` to `use Phoenix.Router` in `app_web.ex`

```elixir
  def router do
    quote do
      use Phoenix.Router, helpers: true
```

I'm then faced with another error but unsure if it's a Kaffy issue or I configured something incorrectly. I'll post more detail if I actually determine.

```
(exit) an exception was raised:
    ** (MatchError) no match of right hand side value: :undefined
        (kaffy 0.9.4) lib/kaffy/utils.ex:370: Kaffy.Utils.setup_resources/0
        (kaffy 0.9.4) lib/kaffy/utils.ex:142: Kaffy.Utils.contexts/1
        (kaffy 0.9.4) lib/kaffy/resource_admin.ex:323: Kaffy.ResourceAdmin.collect_widgets/1
        (kaffy 0.9.4) lib/kaffy_web/templates/home/index.html.eex:14: KaffyWeb.HomeView."index.html"/1
        (phoenix_template 1.0.1) lib/phoenix/template.ex:197: Phoenix.Template.render_within_layout/4
        (phoenix_template 1.0.1) lib/phoenix/template.ex:126: Phoenix.Template.render_to_iodata/4
        (phoenix 1.7.1) lib/phoenix/controller.ex:1005: anonymous fn/5 in Phoenix.Controller.template_render_to_iodata/4
        (telemetry 1.2.1) /home/aodhan/development/pipe-spark/projects/leadstrom/leadstrom/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
        (phoenix 1.7.1) lib/phoenix/controller.ex:971: Phoenix.Controller.render_and_send/4
        (kaffy 0.9.4) lib/kaffy_web/controllers/home_controller.ex:1: KaffyWeb.HomeController.action/2
        (kaffy 0.9.4) lib/kaffy_web/controllers/home_controller.ex:1: KaffyWeb.HomeController.phoenix_controller_pipeline/2
        (phoenix 1.7.1) lib/phoenix/router.ex:425: Phoenix.Router.__call__/5
        (leadstrom 0.1.0) lib/leadstrom_web/endpoint.ex:1: LeadstromWeb.Endpoint.plug_builder_call/2
        (leadstrom 0.1.0) lib/plug/debugger.ex:136: LeadstromWeb.Endpoint."call (overridable 3)"/2
        (leadstrom 0.1.0) lib/leadstrom_web/endpoint.ex:1: LeadstromWeb.Endpoint.call/2
        (phoenix 1.7.1) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
        (plug_cowboy 2.6.0) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
        (cowboy 2.9.0) /home/aodhan/development/pipe-spark/projects/leadstrom/leadstrom/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.9.0) /home/aodhan/development/pipe-spark/projects/leadstrom/leadstrom/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.9.0) /home/aodhan/development/pipe-spark/projects/leadstrom/leadstrom/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
```

**Comment by drobban** [comment]
Trying understand how you guys solved this issue.
But I seem to be missing or not understanding how you all solved the first step of the problem related to not finding Phoenix.View.

Is this something you could explain in detail =) Thanks

**Comment by ghenry** [comment]
There's a flag to enable View isn't there?

**Comment by drobban** [comment]
Finally understood the issue. and made a pull request to update the readme

**Comment by KristerV** [comment]
still bumping into this problem since hexdocs isn't updated.

**Comment by drobban** [comment]
> still bumping into this problem since hexdocs isn't updated.

make a pull request. or which hexdoc are you talking about
