### ISSUE TITLE
[BUG] finding assets

### ISSUE THREAD

**Issue by areski** [aesmail/kaffy#62]
Kaffy: Master branch
Phoenix: 1.5

It seems there is an issue with the current master branch, it cannot find the asset.
```elixir
iex [10:14 :: 4] > [info] GET /kaffy/assets/vendors/css/vendor.bundle.base.css
[debug] ** (Phoenix.Router.NoRouteError) no route found for GET /kaffy/assets/vendors/css/vendor.bundle.base.css (ChitChatWeb.Router)
    (chit_chat 0.1.0) lib/phoenix/router.ex:402: ChitChatWeb.Router.call/2
    (chit_chat 0.1.0) lib/chit_chat_web/endpoint.ex:1: ChitChatWeb.Endpoint.plug_builder_call/2
    (chit_chat 0.1.0) lib/plug/debugger.ex:132: ChitChatWeb.Endpoint."call (overridable 3)"/2
    (chit_chat 0.1.0) lib/chit_chat_web/endpoint.ex:1: ChitChatWeb.Endpoint.call/2
    (phoenix 1.5.3) lib/phoenix/endpoint/cowboy2_handler.ex:65: Phoenix.Endpoint.Cowboy2Handler.init/4 
    (cowboy 2.7.0) /home/areski/projects/phoenix/ex-chitchat/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
    (cowboy 2.7.0) /home/areski/projects/phoenix/ex-chitchat/deps/cowboy/src/cowboy_stream_h.erl:320: :cowboy_stream_h.execute/3
    (cowboy 2.7.0) /home/areski/projects/phoenix/ex-chitchat/deps/cowboy/src/cowboy_stream_h.erl:302: :cowboy_stream_h.request_process/3
    (stdlib 3.11) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Screenshots**
![image](https://user-images.githubusercontent.com/53455/83323407-e02ea400-a25e-11ea-8bac-713caf0238d0.png)

**Comment by aesmail** [comment]
You have to change your endpoint settings. I'll update that in README.

from:

```elixir
config Plug.Static,
  at: "/kaffy",
  from: :kaffy,
  gzip: false,
  only: ~w(css img js scss vendor)
```

to

```elixir
config Plug.Static,
  at: "/kaffy",
  from: :kaffy,
  gzip: false,
  only: ~w(assets)
```

**Comment by aesmail** [comment]
Note that the resource index page might not work properly yet.
I'm moving away from datatables. I'm planning to fix that today.

**Comment by josefrichter** [comment]
I'm having the very same problem right now. latest phoenix, latest kaffy

```
[debug] ** (Phoenix.Router.NoRouteError) no route found for GET /kaffy/assets/js/misc.js (BlogWeb.Router)
    (blog 0.1.0) lib/phoenix/router.ex:402: BlogWeb.Router.call/2
    (blog 0.1.0) lib/blog_web/endpoint.ex:1: BlogWeb.Endpoint.plug_builder_call/2
    (blog 0.1.0) lib/plug/debugger.ex:132: BlogWeb.Endpoint."call (overridable 3)"/2
    (blog 0.1.0) lib/blog_web/endpoint.ex:1: BlogWeb.Endpoint.call/2
    (phoenix 1.5.7) lib/phoenix/endpoint/cowboy2_handler.ex:65: Phoenix.Endpoint.Cowboy2Handler.init/4
    (cowboy 2.8.0) /Users/josefrichter/code/phoenix/blog/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
    (cowboy 2.8.0) /Users/josefrichter/code/phoenix/blog/deps/cowboy/src/cowboy_stream_h.erl:300: :cowboy_stream_h.execute/3
    (cowboy 2.8.0) /Users/josefrichter/code/phoenix/blog/deps/cowboy/src/cowboy_stream_h.erl:291: :cowboy_stream_h.request_process/3
    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

endpoint config is

```
plug Plug.Static,
    at: "/kaffy",
    from: :kaffy,
    gzip: false,
    only: ~w(assets)
```

I am not sure the endpoint config is actually correct and pointing to the right directories?

**Comment by josefrichter** [comment]
ok I was able to partially fix this by moving kaffy static plug to the top of the endpoint file.

but one asset still not loading:

```
[debug] ** (Phoenix.Router.NoRouteError) no route found for GET /kaffy/assets/vendors/fontawesome/css/all.css (BlogWeb.Router)
    (blog 0.1.0) lib/phoenix/router.ex:402: BlogWeb.Router.call/2
    (blog 0.1.0) lib/blog_web/endpoint.ex:1: BlogWeb.Endpoint.plug_builder_call/2
    (blog 0.1.0) lib/plug/debugger.ex:132: BlogWeb.Endpoint."call (overridable 3)"/2
    (blog 0.1.0) lib/blog_web/endpoint.ex:1: BlogWeb.Endpoint.call/2
    (phoenix 1.5.7) lib/phoenix/endpoint/cowboy2_handler.ex:65: Phoenix.Endpoint.Cowboy2Handler.init/4
    (cowboy 2.8.0) /Users/josefrichter/code/phoenix/blog/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
    (cowboy 2.8.0) /Users/josefrichter/code/phoenix/blog/deps/cowboy/src/cowboy_stream_h.erl:300: :cowboy_stream_h.execute/3
    (cowboy 2.8.0) /Users/josefrichter/code/phoenix/blog/deps/cowboy/src/cowboy_stream_h.erl:291: :cowboy_stream_h.request_process/3
    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

is that a bug?

**Comment by aesmail** [comment]
That's weird. Did it just stop working suddenly or was it because you just upgraded to master?
Are you using phoenix master by any chance?

**Comment by josefrichter** [comment]
> That's weird. Did it just stop working suddenly or was it because you just upgraded to master?
> Are you using phoenix master by any chance?

Yesterday I installed Phoenix 1.5.7, started a dummy project and tried to add Kaffy. All other assets seem to work, except the font awesome css. Indeed only icons seem to be missing in the UI, everything else works fine.

**Comment by osluf** [comment]
> ok I was able to partially fix this by moving kaffy static plug to the top of the endpoint file.

@aesmail Phoenix 1.6.9 here, had to do the same thing. For now, only favicon is not being found (404).

**Comment by osluf** [comment]
I'm running on master BTW.

**Comment by azyzz228** [comment]
> ok I was able to partially fix this by moving kaffy static plug to the top of the endpoint file.

Latest Phoenix Version (1.7.7 or 1.7.2 in `mix.exs`). That did the trick for me too
